# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20160520_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
