# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20160521_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='beer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='brewer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.CharField(max_length=30),
        ),
    ]
